### ISSUE TITLE
can we add another interface for one day weather

### ISSUE THREAD

**Issue by maybetaken** [Peiiii/weatherChina#1]
add humidity and  wind speed

**Comment by maybetaken** [comment]
By the way, feel free to assign me to fix this

**Comment by Peiiii** [comment]
Okay, Thank you for your interest in this project. You are welcome to add new
&nbsp;modules or improve the original code. I have already added you as a collaborator. You can fix this and I will be grateful for it.
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Send time:&nbsp;Tuesday, Mar 16, 2021 10:13 PM
***@***.***&gt;; 
***@***.***&gt;; 
Subject: &nbsp;Re: [Peiiii/weatherChina] can we add another interface for one day weather (#1)





 
By the way, feel free to assign me to fix this

**Comment by Peiiii** [comment]
> By the way, feel free to assign me to fix this

Okay, Thank you for your interest in this project. You are welcome to add new modules or improve the original code. I have already added you as a collaborator. You can fix this and I will be grateful for it.

**Comment by maybetaken** [comment]
Done for this.
